### ISSUE TITLE
affconfig.h is missing

### ISSUE THREAD

**Issue by mmulazzani** [simsong/AFFLIBv3#1]
Respectively affconfig.h.in:

~/git_AFFLIBv3$ automake
configure.ac:14: required file `affconfig.h.in' not found

**Comment by mmulazzani** [comment]
Issue has been resolved, sorry!

**Comment by simsong** [comment]
Did you run bootstrap.sh?

From my HTC Sensation 4G on T-Mobile. The first nationwide 4G network

----- Reply message -----
From: "Martin Mulazzani" reply@reply.github.com
To: "Simson L. Garfinkel" simsong@acm.org
Subject: [AFFLIBv3] affconfig.h is missing (#1)
Date: Thu, Jun 28, 2012 10:47 am

Respectively affconfig.h.in:

~/git_AFFLIBv3$ automake
configure.ac:14: required file `affconfig.h.in' not found

---

Reply to this email directly or view it on GitHub:
https://github.com/simsong/AFFLIBv3/issues/1

**Comment by simsong** [comment]
Did you run bootstrap.sh? 

From my HTC Sensation 4G on T-Mobile. The first nationwide 4G network

----- Reply message -----
From: "Martin Mulazzani" reply@reply.github.com
To: "Simson L. Garfinkel" simsong@acm.org
Subject: [AFFLIBv3] affconfig.h is missing (#1)
Date: Thu, Jun 28, 2012 10:47 am

Respectively affconfig.h.in:

~/git_AFFLIBv3$ automake
configure.ac:14: required file `affconfig.h.in' not found

---

Reply to this email directly or view it on GitHub:
https://github.com/simsong/AFFLIBv3/issues/1
