### ISSUE TITLE
size_t strlcpy & strlcat problem - OSX/Mavericks related

### ISSUE THREAD

**Issue by ventz** [simsong/AFFLIBv3#10]
Hi,

Found another issue. The library now compiles (after that patch and the push of the latest tarball), but there is another issue:

```
In file included from ./aff.h:23:


/usr/local/include/afflib/afflib_i.h:660:8: error: expected parameter declarator
size_t strlcpy(char *dest,const char *src,size_t dest_size);
       ^
/usr/include/secure/_string.h:105:44: note: expanded from macro 'strlcpy'
  __builtin___strlcpy_chk (dest, src, len, __darwin_obsz (dest))
                                           ^
/usr/include/secure/_common.h:39:62: note: expanded from macro '__darwin_obsz'
#define __darwin_obsz(object) __builtin_object_size (object, _USE_FORTIF...
                                                             ^
/usr/include/secure/_common.h:30:32: note: expanded from macro
      '_USE_FORTIFY_LEVEL'
#    define _USE_FORTIFY_LEVEL 2
                               ^
```

It looks again like more "awesomeness" from Apple - specific to Mavericks.

One option is to add this to the compile:

```
-D_FORTIFY_SOURCE=0
```

That would be a hack however.

The "proper" solution is to not re-define strlcpy and strlcat in afflib_i.h (starting at line 659 to 665).
The issue is that if you are not using the Apple version of string.h (in this case), you do want them defined, so you can't just get rid of them - there needs to be a check.

I'll try to create a patch and submit a pull request.

**Comment by ventz** [comment]
Ok. Added the fix (a proper one, with a check in the lib), and did a pull request.

**Comment by simsong** [comment]
I think that your patch is wrong. Can you check your `configure.ac` file and see if there is a test for `strlcpy`?

**Comment by simsong** [comment]
Okay. I think that I understand your problem. AFFLIB is compiling just fine on your system, but you are including it in **_ANOTHER PROJECT**_ and that project is not testing for strlcpy in its `configure.ac` file. I think that your patch breaks AFFLIB on other platforms that do not have `strlcpy`.

**Comment by ventz** [comment]
Interesting. Is the check not firing correctly?

There isn't anything in configure.ac by the way(this is for sleuthkit)

What I noticed is that even though there is a check for HAVE_STR**\* in afflib_i.h, it doesn't seem to get called correctly, but that would make sense if it was never in the configure - which is for SleuthKit and not afflib.

**Comment by simsong** [comment]
This is a known sleuthkit bug that has been separately reported. Sleuthkit’s configure.ac file is missing the check. It needs to be added there.

The problem is not AFFLIB.

**Comment by ventz** [comment]
I submitted the info on Sleuthkit's github page. Hopefully they will patch. I wonder why they haven't if they knew about it. This is something very small and simple, yet it effects so many users.

Thanks for looking into it by the way, and for the information.
