### ISSUE TITLE
http://afflib.org/

### ISSUE THREAD

**Issue by mattdreher** [simsong/AFFLIBv3#12]
http://afflib.org/ is listed in the readme documentation many times but the domain doesn't seem to exist.

**Comment by simsong** [comment]
True, but AFFLIBv3 is deprecated.
What are you using it for?

**Comment by mattdreher** [comment]
I didn't know it was deprecated.  Sorry to bother you.  I will use an EnCase image.
I saw this from http://www.forensicswiki.org/wiki/AFF.

**Comment by simsong** [comment]
Okay. I updated the page to make things make more clear.
