### ISSUE TITLE
tools/affuse.c license

### ISSUE THREAD

**Issue by eribertomota** [simsong/AFFLIBv3#15]
The current file says: "License: LGP", when the old files are saying: "License: LGPL or AFFLIB. Take your choice.".

Please, fix this.

Cheers,

Eriberto

**Comment by simsong** [comment]
Sorry, I'm not maintaining this anymore. You can fix it and submit a pull request.

**Comment by sshock** [comment]
I've never done a pull request before, and I don't use git on a regular
basis, but I'll give it a go..
