### ISSUE TITLE
Typo singed/signed in README

### ISSUE THREAD

**Issue by hartwork** [simsong/AFFLIBv3#18]
```
--- AFF allows files to be digital singed, to provide for
+++ AFF allows files to be digital signed, to provide for
                                     ^^
```

https://github.com/simsong/AFFLIBv3/blob/82511e26b8920334c86a970ea19de3cdc84b4e5e/README#L19

**Comment by eribertomota** [comment]
Hi! The AFFLIBv3 is being maintained here[1] now.

Regards,

Eriberto

[1] https://github.com/sshock/AFFLIBv3

**Comment by hartwork** [comment]
I see. Can you make the GitHub project header say so?

**Comment by simsong** [comment]
How?

**Comment by hartwork** [comment]
There is a place near the very top saying "AFF is an open and extensible file format to store disk images and associated metadata." and a (not yet used) URL option next to it. Personally, I believe that would be the best place for a few words and the URL to direct to the other repository. Maybe even in all caps.

**Comment by simsong** [comment]
Done.

**Comment by hartwork** [comment]
Excellent, thank you!
