### ISSUE TITLE
"FUSE IS NOT SUPPORTED ON MACOS"

### ISSUE THREAD

**Issue by dkovar** [simsong/AFFLIBv3#4]
Good afternoon,

This message shows up in config.log when trying to build afflib on OS X. It appears to be hardwired into configure and fires even if configure can find and use fuse.h.

I've successfully built and used libewf with FUSE support on the same system, so I'm curious why this support isn't available in afflib.

Thank you.

-David

**Comment by dkovar** [comment]
I took the check for Darwin out of config.ac and ran configure with:

CPPFLAGS="-DFUSE_USE_VERSION=26 -I/usr/local/include/osxfuse" ./configure

And it works:

affuse@osxfuse0 on /Volumes/FreeAgent GoFlex Drive/Acquired Images/<system name>/mnt (osxfusefs, nodev, nosuid, synchronous, mounted by kovar)

Spoke too soon: 

Praha: kovar$ cd mnt
-bash: cd: mnt: Input/output error

**Comment by simsong** [comment]
AFFLIBv3 is in maintenance mode. I am no longer actively developing it. If you want to make FUSE work, you are welcome to do so. Please fork AFFLIBv3, get the feature to work, and then send me a pull request. Thanks.
